### ISSUE TITLE
Lingering Owned Territories after surrender

### ISSUE THREAD

**Issue by Alzarath** [ElectricPrism/Risk_Action_Edition_II#2]
After surrendering to another player, I noticed the game said I still had 3 territories remaining where I clearly had none. I continued to get income for it.

**Comment by Alzarath** [comment]
After another game, I can verify this is reproducible by surrendering. Not sure if it still thinks you own all of the territories you did before surrendering, but it's definitely a large percetange of them.

**Comment by ElectricPrism** [comment]
Income is calculated as follows:

If a player has 4 or fewer territories they receive a minimum income of $9.

This included if you owned 0 territories. I have updated it to incentivize idling players to hold at least 1 territory.

When you own 5 or more territories the payout is $2 per territory so 5 T = $10, etc...

There may be a second issue where the leaderboard and territory custom resource may be drawing wrong as they are only redrawn on count update. If so please make a note in a new bug.

I think this part of the bug is fixed, but if not reopen.
