### ISSUE TITLE
Territories sometimes return to owner after being taken

### ISSUE THREAD

**Issue by Alzarath** [ElectricPrism/Risk_Action_Edition_II#5]
I noticed, especially when flying by with a Dropship to nab a territory, they will return to their original owner. Since it seems to use an 'enter region' trigger of some kind, if this happens and the unit doesn't leave, he'll just stand there and not take over the territory until you leave and re-enter the beacon, surely taking at least a few extra shots.

**Comment by ElectricPrism** [comment]
I believe there are several events that trigger a Territory Ownership Check [<RAE> CheckAllTerritoriesOwnership()]

- The death of a offensive or defensive unit with X range of the Territory center
- A unit entering a region or point

Maybe the triggers see unloading the unit as "cargo" and slip by the default checks.

I have thought about the costs/benefits to the Risk Legacy style of attacking and destroying the cannon but I feel like the existing method is more classical and true to what people preferred from the SC1 version.

Also noteworthy is that air units are completely ignored by the triggers specifically because we saw a lot of drive-by takeovers since the suckers move so fast.

If you have any other information that would help, thanks, I will see if there is a quick fix.

**Comment by ElectricPrism** [comment]
I cloned the check:

"CE Rules | Any Unit Dies? Check Territory Ownership"

to become:

"CE Rules | Any Unit Is Unloaded? Check Territory Ownership"

Basically it checks if a cargo unit is unloaded in any of the 44 Territory zones and if so will reassign ownership if there is no contesting unit.
